### ISSUE TITLE
snakemake not installing with pip install dahak_taco

### ISSUE THREAD

**Issue by ljcohen** [dahak-metagenomics/dahak-taco#4]
So, as someone who doesn't follow installation instructions very well...

With these steps, `dahak_taco` appears to install:
```
conda create -n dahak python=3
source activate dahak
pip install dahak_taco
```
But this error occurs:
```
(dahak) campus-014-079:~ johnsolk$ taco --help
Traceback (most recent call last):
  File "/Users/johnsolk/anaconda3/envs/dahak/bin/taco", line 7, in <module>
    from cli.command import main
  File "/Users/johnsolk/anaconda3/envs/dahak/lib/python3.6/site-packages/cli/command.py", line 3, in <module>
    import snakemake
ModuleNotFoundError: No module named 'snakemake'
```
To fix:
```
pip install snakemake
```
Seems to work!
```
(dahak) campus-014-079:~ johnsolk$ taco --help
usage: taco [-h] [--config-json CONFIG_JSON | --config-yaml CONFIG_YAML]
            [--params-json PARAMS_JSON | --params-yaml PARAMS_YAML] [-c] [-f]
            [-n] [--prefix PREFIX]
            [verb [verb ...]]

positional arguments:
  verb                  The verb to perform or the name of the workflow to run

optional arguments:
  -h, --help            show this help message and exit
  --config-json CONFIG_JSON
                        Specify a workflow configuration file in JSON format
  --config-yaml CONFIG_YAML
                        Specify a workflow configuration file in YAML format
  --params-json PARAMS_JSON
                        Specify a workflow parameters file in JSON format
  --params-yaml PARAMS_YAML
                        Specify a workflow parameters file in YAML format
  -c, --clean           Use a clean, empty default Snakemake parameters
                        dictionary. Used for testing and debugging.
  -f, --force           Force Snakemake to run all rules in the workflow, even
                        if target files already exist.
  -n, --dry-run         Do a dry run with Snakemake: assemble but do not run
                        the task graph.
  --prefix PREFIX       Set the working directory where all files are
                        generated.
```

**Comment by charlesreid1** [comment]
Okay - thanks for creating the issue. I did not have snakemake in the requirements.txt file!
